# Generated by Django 3.2 on 2021-10-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
